var _ = require('underscore');
var log = require('./log');

var files = [
    require('./sprites/agent'),
    require('./sprites/arrow'),
    require('./sprites/axe'),
    require('./sprites/bat'),
    require('./sprites/beachnpc'),
    require('./sprites/bluesword'),
    require('./sprites/boss'),
    require('./sprites/chest'),
    require('./sprites/clotharmor'),
    require('./sprites/coder'),
    require('./sprites/crab'),
    require('./sprites/death'),
    require('./sprites/deathknight'),
    require('./sprites/desertnpc'),
    require('./sprites/eye'),
    require('./sprites/firefox'),
    require('./sprites/forestnpc'),
    require('./sprites/goblin'),
    require('./sprites/goldenarmor'),
    require('./sprites/goldensword'),
    require('./sprites/guard'),
    require('./sprites/hand'),
    require('./sprites/impact'),
    require('./sprites/item-axe'),
    require('./sprites/item-bluesword'),
    require('./sprites/item-burger'),
    require('./sprites/item-cake'),
    require('./sprites/item-firepotion'),
    require('./sprites/item-flask'),
    require('./sprites/item-goldenarmor'),
    require('./sprites/item-goldensword'),
    require('./sprites/item-leatherarmor'),
    require('./sprites/item-mailarmor'),
    require('./sprites/item-morningstar'),
    require('./sprites/item-platearmor'),
    require('./sprites/item-redarmor'),
    require('./sprites/item-redsword'),
    require('./sprites/item-sword1'),
    require('./sprites/item-sword2'),
    require('./sprites/king'),
    require('./sprites/lavanpc'),
    require('./sprites/leatherarmor'),
    require('./sprites/loot'),
    require('./sprites/mailarmor'),
    require('./sprites/morningstar'),
    require('./sprites/nyan'),
    require('./sprites/octocat'),
    require('./sprites/ogre'),
    require('./sprites/platearmor'),
    require('./sprites/priest'),
    require('./sprites/rat'),
    require('./sprites/redarmor'),
    require('./sprites/redsword'),
    require('./sprites/rick'),
    require('./sprites/scientist'),
    require('./sprites/shadow16'),
    require('./sprites/skeleton'),
    require('./sprites/skeleton2'),
    require('./sprites/snake'),
    require('./sprites/sorcerer'),
    require('./sprites/sparks'),
    require('./sprites/spectre'),
    require('./sprites/sword'),
    require('./sprites/sword1'),
    require('./sprites/sword2'),
    require('./sprites/talk'),
    require('./sprites/target'),
    require('./sprites/villagegirl'),
    require('./sprites/villager'),
    require('./sprites/wizard')
];

var sprites = {};

_.each(files, function(sprite) {
    sprites[sprite.id] = sprite;
});

module.exports = sprites;
